version: '3.8'

services:
  onlinestore:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: onlinestore
    stdin_open: true
    tty: true
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app
    command: python src/orders.py
